name: build and test
on: [push, pull_request]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18.0'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libvips
      - run: make build
      - run: make test
