name: build and test
on: [push, pull_request]
jobs:
  build_test:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'
      - run: make build
      - run: make test
