name: release
  # tags only
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@
        with:
          go-version: '^1.18.0'
      - uses: actions/setup-node@v3
          node-version: 16
      - run: apt-get update
      - run: apt-get install mingw-w64 -y
      - run: make build-all
      - run: ls dist -lh
