name: release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.18.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt-get update
      - run: sudo apt-get install mingw-w64 -y
      - run: make build-all
      - run: gh release create $(git describe --tags --always) --generate-notes

